name: CharlenesCoffeeCorner CI
on: 
  pull_request:
    branches: [dev, master]
  push:
    branches: [dev, master]
jobs:
  CharlenesCoffeeCorner-Job:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Maven Test
        if: ${{ github.event_name == 'pull_request' }}
        run: mvn test 

      - name: Maven Package
        if: ${{ github.event_name == 'push' }}
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: ${{ ( github.event_name == 'push' )  &&  ( github.ref == 'refs/heads/master' ) }}
        with:
          name: CharlenesCoffeeCorner-Artifact
          path: target/CharlenesCoffeeCorner-1.0-SNAPSHOT.jar
        